@echo off
REM ============================================================================
REM Comfy Workflow - Hunyuan-Image 2.1 (3 variants: fp8 + bf16 + distilled fp8)
REM ============================================================================
REM Generated by installer/benchmark/generate_install_scripts.py
REM DO NOT EDIT BY HAND. Re-generate via:
REM   python -m installer.benchmark.generate_install_scripts
REM ============================================================================
REM Pillars: #3
REM Models (from models_manifest.yaml): hunyuan_image_21_fp8, hunyuan_image_21_bf16, hunyuan_image_21_distilled_fp8, hunyuan_shared_encoders, hunyuan_shared_vae
REM Hardware minimo: 48 GB RAM, 16 GB VRAM
REM Total download (this script): ~81.55 GiB
REM ============================================================================
setlocal EnableDelayedExpansion

set "REPO_RAW=https://raw.githubusercontent.com/comfyworkflow/comfy-workflow/main"
set "CATEGORY=Image\Hunyuan"

REM ----- Pre-req: ComfyUI base install must exist -----
REM The detailed ERROR block below is for users who downloaded this
REM .bat without running 01-install-base.bat first. YouTube channel
REM link restrictions (DA: external-channel links banned) mean the
REM audience cannot navigate via playlists — so this block embeds the
REM repo URL, the file name to fetch, and the Video #1 tutorial URL
REM directly. {INSTALL_BASE_URL} is substituted at generation time
REM from the manifest videos: section (empty => "Coming soon").
if not exist "C:\ComfyUI_windows_portable\ComfyUI\main.py" (
    echo.
    echo =========================================================================
    echo   ERROR: ComfyUI base install not found
    echo =========================================================================
    echo.
    echo   This install needs ComfyUI base installed FIRST.
    echo   Step 1 of the series - you skipped it.
    echo.
    echo   How to fix:
    echo.
    echo    1. Open:           https://github.com/comfyworkflow/comfy-workflow
    echo    2. Click folder:   setup-windows
    echo    3. Download:       01-install-base.bat
    echo    4. Run it          ^(installs ComfyUI portable + essential nodes^)
    echo    5. Come back and run this script again
    echo.
    echo   Tutorial video ^(Video #1 - ComfyUI base^):
    echo   https://youtu.be/PZmJqxP5ajs
    echo.
    echo =========================================================================
    if not defined COMFY_NONINTERACTIVE pause
    exit /b 1
)

goto :main

REM ============================================================================
REM Subroutine: download_or_skip
REM   %1 = url
REM   %2 = absolute target path
REM   %3 = expected size in bytes (string compare; no int32 limit)
REM ============================================================================
:download_or_skip
set "URL=%~1"
set "TARGET=%~2"
set "EXPECTED=%~3"
if exist "!TARGET!" (
    for %%A in ("!TARGET!") do set "ACTUAL=%%~zA"
    if "!ACTUAL!"=="!EXPECTED!" (
        echo   Skip ^(size match^): !TARGET!
        goto :eof
    )
    echo   Re-downloading ^(size mismatch !ACTUAL! != !EXPECTED!^): !TARGET!
    del "!TARGET!" >nul 2>&1
)
echo   Downloading: !URL!
curl.exe -L --fail --progress-bar --retry 3 --retry-delay 5 -o "!TARGET!" "!URL!"
if !ERRORLEVEL! NEQ 0 (
    echo   ERROR: download failed for !URL!
    exit /b 1
)
for %%A in ("!TARGET!") do set "ACTUAL=%%~zA"
if not "!ACTUAL!"=="!EXPECTED!" (
    echo   ERROR: post-download size mismatch ^(!ACTUAL! != !EXPECTED!^): !TARGET!
    exit /b 1
)
echo   OK ^(verified !EXPECTED! bytes^): !TARGET!
goto :eof

REM ============================================================================
REM Subroutine: ensure_custom_node
REM   %1 = folder name (e.g. ComfyUI-GGUF)
REM   %2 = git repo URL
REM ============================================================================
:ensure_custom_node
set "NODE_NAME=%~1"
set "NODE_DIR=C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\!NODE_NAME!"
set "REPO=%~2"
if exist "!NODE_DIR!" (
    echo   Custom node already present: !NODE_NAME!
    goto :eof
)
echo   Cloning custom node: !NODE_NAME!
git clone "!REPO!" "!NODE_DIR!"
if !ERRORLEVEL! NEQ 0 (
    echo   ERROR: git clone failed for !NODE_NAME!
    exit /b 1
)
goto :eof

REM ============================================================================
REM Subroutine: ship_workflow
REM   %1 = workflow filename (e.g. sdxl_base.json)
REM Downloads the Format B distribute version from
REM "workflows_distribute/!CATEGORY_URL!/!WF_JSON!" (URL form: forward
REM slashes) into the matching local sidebar subfolder
REM "Comfy Workflow\!CATEGORY!\" (Windows form: backslashes). The
REM repo source path and the user-visible category share the same
REM hierarchy, so audience and repo browsers see the same structure.
REM The .md sidecar is NOT shipped — its content is embedded as a Note
REM node inside the Format B workflow, so the audience sees the bula
REM directly on the canvas (sidebar Workflows -> Comfy Workflow ->
REM !CATEGORY! -> click).
REM ============================================================================
:ship_workflow
set "WF_JSON=%~1"
set "DEST_BASE=C:\ComfyUI_windows_portable\ComfyUI\user\default\workflows\Comfy Workflow"
set "DEST_DIR=!DEST_BASE!\!CATEGORY!"
set "CATEGORY_URL=!CATEGORY:\=/!"
if not exist "!DEST_DIR!" mkdir "!DEST_DIR!"
echo   Shipping workflow: !WF_JSON! ^(category: !CATEGORY!^)
curl.exe -L --fail --silent --retry 3 --retry-delay 5 -o "!DEST_DIR!\!WF_JSON!" "!REPO_RAW!/installer/benchmark/workflows_distribute/!CATEGORY_URL!/!WF_JSON!"
if !ERRORLEVEL! NEQ 0 (
    echo   ERROR: download failed for !WF_JSON!
    exit /b 1
)
goto :eof

REM ============================================================================
REM Subroutine: cleanup_flat_workflows
REM   %1 = glob pattern (e.g. sdxl_*.json)
REM Removes flat-layout workflow files from the legacy
REM "Comfy Workflow\Image\" folder. The new layout lives under
REM "Comfy Workflow\Image\<FAMILY>\" so installs from this script
REM will populate the family subfolder; this subroutine prunes
REM stale flat siblings left over from prior installs to avoid
REM duplicate workflows showing up in the audience's sidebar.
REM ============================================================================
:cleanup_flat_workflows
set "PATTERN=%~1"
set "FLAT_DIR=C:\ComfyUI_windows_portable\ComfyUI\user\default\workflows\Comfy Workflow\Image"
if not exist "!FLAT_DIR!" goto :eof
for %%F in ("!FLAT_DIR!\!PATTERN!") do (
    if exist "%%F" (
        echo   Removing legacy flat workflow: %%~nxF
        del "%%F" >nul 2>&1
    )
)
goto :eof

:main

echo.
echo ========================================================
echo  Comfy Workflow - Hunyuan-Image 2.1 (3 variants: fp8 + bf16 + distilled fp8)
echo ========================================================
echo  Pillars: #3
echo  Hardware minimo: 48 GB RAM, 16 GB VRAM
echo  Total download: ~81.55 GiB
echo ========================================================
echo.

REM ----- Pre-create model folders (idempotent) -----
if not exist "C:\ComfyUI_windows_portable\ComfyUI\models\checkpoints"      mkdir "C:\ComfyUI_windows_portable\ComfyUI\models\checkpoints"
if not exist "C:\ComfyUI_windows_portable\ComfyUI\models\diffusion_models" mkdir "C:\ComfyUI_windows_portable\ComfyUI\models\diffusion_models"
if not exist "C:\ComfyUI_windows_portable\ComfyUI\models\text_encoders"    mkdir "C:\ComfyUI_windows_portable\ComfyUI\models\text_encoders"
if not exist "C:\ComfyUI_windows_portable\ComfyUI\models\vae"              mkdir "C:\ComfyUI_windows_portable\ComfyUI\models\vae"
if not exist "C:\ComfyUI_windows_portable\ComfyUI\user\default\workflows\Comfy Workflow" mkdir "C:\ComfyUI_windows_portable\ComfyUI\user\default\workflows\Comfy Workflow"

echo [1/3] Downloading model files (total: ~81.55 GiB)...
call :download_or_skip "https://huggingface.co/Comfy-Org/HunyuanImage_2.1_ComfyUI/resolve/main/split_files/diffusion_models/hunyuanimage2.1_fp8_e4m3fn.safetensors" "C:\ComfyUI_windows_portable\ComfyUI\models\diffusion_models\hunyuanimage2.1_fp8_e4m3fn.safetensors" 17425920656
call :download_or_skip "https://huggingface.co/Comfy-Org/HunyuanImage_2.1_ComfyUI/resolve/main/split_files/diffusion_models/hunyuanimage2.1_bf16.safetensors" "C:\ComfyUI_windows_portable\ComfyUI\models\diffusion_models\hunyuanimage2.1_bf16.safetensors" 34851687040
call :download_or_skip "https://huggingface.co/Comfy-Org/HunyuanImage_2.1_ComfyUI/resolve/main/split_files/diffusion_models/hunyuanimage2.1_distilled_fp8_e4m3fn.safetensors" "C:\ComfyUI_windows_portable\ComfyUI\models\diffusion_models\hunyuanimage2.1_distilled_fp8_e4m3fn.safetensors" 17453462000
call :download_or_skip "https://huggingface.co/Comfy-Org/HunyuanImage_2.1_ComfyUI/resolve/main/split_files/text_encoders/qwen_2.5_vl_7b.safetensors" "C:\ComfyUI_windows_portable\ComfyUI\models\text_encoders\qwen_2.5_vl_7b.safetensors" 16584415576
call :download_or_skip "https://huggingface.co/Comfy-Org/HunyuanImage_2.1_ComfyUI/resolve/main/split_files/text_encoders/byt5_small_glyphxl_fp16.safetensors" "C:\ComfyUI_windows_portable\ComfyUI\models\text_encoders\byt5_small_glyphxl_fp16.safetensors" 438643184
call :download_or_skip "https://huggingface.co/Comfy-Org/HunyuanImage_2.1_ComfyUI/resolve/main/split_files/vae/hunyuan_image_2.1_vae_fp16.safetensors" "C:\ComfyUI_windows_portable\ComfyUI\models\vae\hunyuan_image_2.1_vae_fp16.safetensors" 811184822

echo [2/3] Pruning legacy flat-layout workflow files (hunyuan_*.json)...
call :cleanup_flat_workflows "hunyuan_*.json"

echo [3/3] Shipping 3 workflow file(s)...
call :ship_workflow "hunyuan_image_21_fp8.json"
call :ship_workflow "hunyuan_image_21_bf16.json"
call :ship_workflow "hunyuan_image_21_distilled_fp8.json"

echo.
echo =========================================================================
echo   Hunyuan-Image 2.1 install complete^^!
echo =========================================================================
echo.
echo   Models installed: 2.1 fp8 (17.4 GB) + 2.1 bf16 (34.9 GB) + 2.1 distilled fp8 (17.5 GB) + dual encoders (qwen + byt5, 17 GB) + VAE (0.8 GB) - total ~88 GB
echo.
echo   Workflows in ComfyUI sidebar:
echo     Comfy Workflow ^> Image ^> Hunyuan ^> (3 variants: fp8 / bf16 / distilled-8-step)
echo.
echo   Default recommendation: hunyuan_image_21_fp8.json (Quality 50-step, ~60s on RTX 5090, 16 GB VRAM)
echo   For fast iteration: hunyuan_image_21_distilled_fp8.json (8-step meanflow, ~10s warm)
echo   For reference precision: hunyuan_image_21_bf16.json (24 GB+ VRAM recommended)
echo   Native 2K only - do NOT generate at 1024x1024 (model produces artifacts). See workflow Note for 2K aspect buckets.
echo.
echo   Tutorial video ^(Video #5 - Hunyuan-Image 2.1 install + benchmark^):
echo   (Coming soon - watch the repo for updates)
echo.
echo   Next in series ^(Video #6 - WAN 2.2^):
echo   (Coming soon - watch the repo for updates)
echo.
echo   Repo ^(all installs^):
echo   https://github.com/comfyworkflow/comfy-workflow
echo.
echo =========================================================================
echo.
if not defined COMFY_NONINTERACTIVE pause
endlocal
exit /b 0
