@echo off
REM ============================================================================
REM Comfy Workflow - SDXL Base 1.0
REM ============================================================================
REM Generated by installer/benchmark/generate_install_scripts.py
REM DO NOT EDIT BY HAND. Re-generate via:
REM   python -m installer.benchmark.generate_install_scripts
REM ============================================================================
REM Pillars: #1
REM Models (from models_manifest.yaml): sdxl_base_1.0
REM Hardware minimo: 16 GB RAM, 8 GB VRAM
REM Total download (this script): ~6.46 GiB
REM ============================================================================
setlocal EnableDelayedExpansion

set "REPO_RAW=https://raw.githubusercontent.com/comfyworkflow/comfy-workflow/main"
set "CATEGORY=Image"

REM ----- Pre-req: ComfyUI base install must exist -----
if not exist "C:\ComfyUI_windows_portable\ComfyUI\main.py" (
    echo.
    echo ERROR: ComfyUI base install not found.
    echo.
    echo   Expected at: C:\ComfyUI_windows_portable\ComfyUI\main.py
    echo.
    echo Run 01-install-base.bat first, then re-run this script.
    echo.
    if not defined COMFY_NONINTERACTIVE pause
    exit /b 1
)

goto :main

REM ============================================================================
REM Subroutine: download_or_skip
REM   %1 = url
REM   %2 = absolute target path
REM   %3 = expected size in bytes (string compare; no int32 limit)
REM ============================================================================
:download_or_skip
set "URL=%~1"
set "TARGET=%~2"
set "EXPECTED=%~3"
if exist "!TARGET!" (
    for %%A in ("!TARGET!") do set "ACTUAL=%%~zA"
    if "!ACTUAL!"=="!EXPECTED!" (
        echo   Skip ^(size match^): !TARGET!
        goto :eof
    )
    echo   Re-downloading ^(size mismatch !ACTUAL! != !EXPECTED!^): !TARGET!
    del "!TARGET!" >nul 2>&1
)
echo   Downloading: !URL!
curl.exe -L --fail --progress-bar --retry 3 --retry-delay 5 -o "!TARGET!" "!URL!"
if !ERRORLEVEL! NEQ 0 (
    echo   ERROR: download failed for !URL!
    exit /b 1
)
for %%A in ("!TARGET!") do set "ACTUAL=%%~zA"
if not "!ACTUAL!"=="!EXPECTED!" (
    echo   ERROR: post-download size mismatch ^(!ACTUAL! != !EXPECTED!^): !TARGET!
    exit /b 1
)
echo   OK ^(verified !EXPECTED! bytes^): !TARGET!
goto :eof

REM ============================================================================
REM Subroutine: ensure_custom_node
REM   %1 = folder name (e.g. ComfyUI-GGUF)
REM   %2 = git repo URL
REM ============================================================================
:ensure_custom_node
set "NODE_NAME=%~1"
set "NODE_DIR=C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\!NODE_NAME!"
set "REPO=%~2"
if exist "!NODE_DIR!" (
    echo   Custom node already present: !NODE_NAME!
    goto :eof
)
echo   Cloning custom node: !NODE_NAME!
git clone "!REPO!" "!NODE_DIR!"
if !ERRORLEVEL! NEQ 0 (
    echo   ERROR: git clone failed for !NODE_NAME!
    exit /b 1
)
goto :eof

REM ============================================================================
REM Subroutine: ship_workflow
REM   %1 = workflow filename (e.g. sdxl_base.json)
REM Downloads the Format B distribute version into the
REM "Comfy Workflow\!CATEGORY!\" sidebar subfolder. The .md sidecar is
REM NOT shipped — its content is embedded as a Note node inside the
REM Format B workflow, so the audience sees the bula directly on the
REM canvas (sidebar Workflows -> Comfy Workflow -> !CATEGORY! -> click).
REM ============================================================================
:ship_workflow
set "WF_JSON=%~1"
set "DEST_BASE=C:\ComfyUI_windows_portable\ComfyUI\user\default\workflows\Comfy Workflow"
set "DEST_DIR=!DEST_BASE!\!CATEGORY!"
if not exist "!DEST_DIR!" mkdir "!DEST_DIR!"
echo   Shipping workflow: !WF_JSON! ^(category: !CATEGORY!^)
curl.exe -L --fail --silent --retry 3 --retry-delay 5 -o "!DEST_DIR!\!WF_JSON!" "!REPO_RAW!/installer/benchmark/workflows_distribute/!WF_JSON!"
if !ERRORLEVEL! NEQ 0 (
    echo   ERROR: download failed for !WF_JSON!
    exit /b 1
)
goto :eof

:main

echo.
echo ========================================================
echo  Comfy Workflow - SDXL Base 1.0
echo ========================================================
echo  Pillars: #1
echo  Hardware minimo: 16 GB RAM, 8 GB VRAM
echo  Total download: ~6.46 GiB
echo ========================================================
echo.

REM ----- Pre-create model folders (idempotent) -----
if not exist "C:\ComfyUI_windows_portable\ComfyUI\models\checkpoints"      mkdir "C:\ComfyUI_windows_portable\ComfyUI\models\checkpoints"
if not exist "C:\ComfyUI_windows_portable\ComfyUI\models\diffusion_models" mkdir "C:\ComfyUI_windows_portable\ComfyUI\models\diffusion_models"
if not exist "C:\ComfyUI_windows_portable\ComfyUI\models\text_encoders"    mkdir "C:\ComfyUI_windows_portable\ComfyUI\models\text_encoders"
if not exist "C:\ComfyUI_windows_portable\ComfyUI\models\vae"              mkdir "C:\ComfyUI_windows_portable\ComfyUI\models\vae"
if not exist "C:\ComfyUI_windows_portable\ComfyUI\user\default\workflows\Comfy Workflow" mkdir "C:\ComfyUI_windows_portable\ComfyUI\user\default\workflows\Comfy Workflow"

echo [1/2] Downloading model files (total: ~6.46 GiB)...
call :download_or_skip "https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/sd_xl_base_1.0.safetensors" "C:\ComfyUI_windows_portable\ComfyUI\models\checkpoints\sd_xl_base_1.0.safetensors" 6938078334

echo [2/2] Shipping workflow files...
call :ship_workflow "sdxl_base.json"

echo.
echo ========================================================
echo  DONE - SDXL Base 1.0
echo ========================================================
echo.
echo  Next steps:
echo    1. Run C:\ComfyUI_windows_portable\run_nvidia_gpu.bat
echo    2. Open ComfyUI in browser, load workflow:
echo        ComfyUI -^> Workflows -^> sdxl_base.json
echo.
if not defined COMFY_NONINTERACTIVE pause
endlocal
exit /b 0
