@echo off
REM ============================================================================
REM Comfy Workflow - Setup Pillar #1 (SDXL Base 1.0)
REM ============================================================================
REM Generated by installer/benchmark/generate_install_scripts.py
REM DO NOT EDIT BY HAND. Re-generate via:
REM   python -m installer.benchmark.generate_install_scripts
REM ============================================================================
REM Master orchestrator: runs 01-install-base.bat + install-sdxl.bat in
REM sequence. For SSH dispatch, set COMFY_NONINTERACTIVE=1 (or pass
REM --unattended / -u as first arg) to suppress pauses and the FIRST
REM LAUNCH manual step in 01-install-base.bat.
REM ============================================================================
setlocal EnableDelayedExpansion

REM ----- Parse --unattended / -u flag (sets COMFY_NONINTERACTIVE) -----
if /i "%~1"=="--unattended" set "COMFY_NONINTERACTIVE=1"
if /i "%~1"=="-u" set "COMFY_NONINTERACTIVE=1"

REM ----- Locate script directory (so we can call sibling .bat files) -----
set "SCRIPT_DIR=%~dp0"
if "!SCRIPT_DIR:~-1!"=="\" set "SCRIPT_DIR=!SCRIPT_DIR:~0,-1!"

echo.
echo ========================================================
echo  Comfy Workflow - Pillar #1 Setup (SDXL Base 1.0)
echo ========================================================
echo.
echo  This will run, in sequence:
echo    [1/2] 01-install-base.bat  (ComfyUI portable + essential nodes)
echo    [2/2] install-sdxl.bat     (SDXL 1.0 model + workflow)
echo.
echo  Hardware minimo (SDXL): 16 GB RAM, 8 GB VRAM
echo  Total download: ~10 GiB (3 GiB ComfyUI portable + 7 GiB SDXL)
echo.
if defined COMFY_NONINTERACTIVE (
    echo  Running unattended ^(COMFY_NONINTERACTIVE=1^).
) else (
    echo  Press any key to continue, or close window to abort.
    pause
)

echo.
echo === [1/2] Running 01-install-base.bat ===
echo.
if not exist "!SCRIPT_DIR!\01-install-base.bat" (
    echo ERROR: 01-install-base.bat not found next to setup-pillar1.bat.
    echo Expected: !SCRIPT_DIR!\01-install-base.bat
    if not defined COMFY_NONINTERACTIVE pause
    exit /b 1
)
call "!SCRIPT_DIR!\01-install-base.bat"
if !ERRORLEVEL! NEQ 0 (
    echo.
    echo ERROR: 01-install-base.bat failed ^(exit !ERRORLEVEL!^).
    if not defined COMFY_NONINTERACTIVE pause
    exit /b 1
)

echo.
echo === [2/2] Running install-sdxl.bat ===
echo.
if not exist "!SCRIPT_DIR!\install-sdxl.bat" (
    echo ERROR: install-sdxl.bat not found next to setup-pillar1.bat.
    echo Expected: !SCRIPT_DIR!\install-sdxl.bat
    if not defined COMFY_NONINTERACTIVE pause
    exit /b 1
)
call "!SCRIPT_DIR!\install-sdxl.bat"
if !ERRORLEVEL! NEQ 0 (
    echo.
    echo ERROR: install-sdxl.bat failed ^(exit !ERRORLEVEL!^).
    if not defined COMFY_NONINTERACTIVE pause
    exit /b 1
)

echo.
echo ========================================================
echo  PILLAR 1 SETUP COMPLETE
echo ========================================================
echo.
echo  Installed:
echo    - ComfyUI Portable (Python 3.13 + CUDA 13.0)
echo    - Essential custom nodes: Manager, rgthree, Crystools
echo    - SDXL Base 1.0 model
echo    - sdxl_base.json workflow + sidecar README
echo.
echo  Next steps:
echo    1. Run C:\ComfyUI_windows_portable\run_nvidia_gpu.bat
echo    2. Open workflow: ComfyUI -^> Workflows -^> sdxl_base.json
echo.
if not defined COMFY_NONINTERACTIVE pause
endlocal
exit /b 0
